# CodeDeploy 버전(프로젝트 버전이 아니므로 0.0 외의 다른 버전을 사용하면 에러 발생)
version: 0.0
os: linux
# CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 지정
# destination(source에서 지정된 파일을 받을 위치)
# overwrite(파일이 해당 위치에 존재한다면 덮어쓰기 여부)
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes